import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

// POST /api/disclosures/sessions/[id]/generate - generate the disclosure document as HTML
export async function POST(_: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id: sessionId } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  // Fetch session with form info
  const { data: session } = await supabase
    .from('disclosure_sessions')
    .select(`*, form:disclosure_forms(*)`)
    .eq('id', sessionId)
    .eq('user_id', user.id)
    .single();

  if (!session) return NextResponse.json({ error: 'Session not found' }, { status: 404 });

  // Fetch questions in order
  const { data: questions } = await supabase
    .from('disclosure_questions')
    .select('*')
    .eq('form_id', session.form_id)
    .order('display_order');

  // Fetch all answers
  const { data: answers } = await supabase
    .from('disclosure_answers')
    .select('*')
    .eq('session_id', sessionId);

  const answerMap: Record<string, { answer_value: string; explanation?: string }> = {};
  (answers || []).forEach(a => { answerMap[a.question_key] = a; });

  // Group into sections
  const sectionOrder: string[] = [];
  const sectionMap: Record<string, { label: string; questions: any[] }> = {};
  (questions || []).forEach(q => {
    if (!sectionMap[q.section_key]) {
      sectionMap[q.section_key] = { label: q.section_label, questions: [] };
      sectionOrder.push(q.section_key);
    }
    sectionMap[q.section_key].questions.push(q);
  });

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const answerLabel = (val: string | undefined) => {
    if (!val) return '<span style="color:#cc0000">Not answered</span>';
    if (val === 'yes') return '<strong style="color:#cc0000">YES</strong>';
    if (val === 'no') return '<strong style="color:#006600">NO</strong>';
    if (val === 'na') return '<em style="color:#666">N/A</em>';
    return val;
  };

  // Build HTML document
  const sectionsHtml = sectionOrder.map(sKey => {
    const section = sectionMap[sKey];
    const questionsHtml = section.questions.map(q => {
      const ans = answerMap[q.question_key];
      const hasExplanation = ans?.explanation;
      return `
        <tr style="border-bottom:1px solid #eee">
          <td style="padding:10px 8px;vertical-align:top;width:60%;font-size:13px">
            <span style="color:#666;font-size:11px">${q.question_number || ''}</span>
            <span style="margin-left:4px">${q.question_text}</span>
          </td>
          <td style="padding:10px 8px;vertical-align:top;font-size:13px;text-align:center;width:12%">
            ${answerLabel(ans?.answer_value)}
          </td>
          <td style="padding:10px 8px;vertical-align:top;font-size:12px;color:#333;width:28%">
            ${hasExplanation ? `<em>${ans.explanation}</em>` : ''}
          </td>
        </tr>`;
    }).join('');

    return `
      <div style="margin-bottom:28px">
        <div style="background:#1a1a2e;color:white;padding:8px 12px;font-weight:bold;font-size:14px;letter-spacing:0.5px">
          ${section.label.toUpperCase()}
        </div>
        <table style="width:100%;border-collapse:collapse;border:1px solid #ddd">
          <thead>
            <tr style="background:#f5f5f5">
              <th style="padding:8px;text-align:left;font-size:12px;color:#555">Question</th>
              <th style="padding:8px;text-align:center;font-size:12px;color:#555">Answer</th>
              <th style="padding:8px;text-align:left;font-size:12px;color:#555">Explanation</th>
            </tr>
          </thead>
          <tbody>${questionsHtml}</tbody>
        </table>
      </div>`;
  }).join('');

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${session.form?.form_name} — ${session.property_address}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 24px; color: #222; font-size: 13px; }
    @media print { body { padding: 0; } .no-print { display: none; } }
  </style>
</head>
<body>
  <!-- Header -->
  <div style="text-align:center;margin-bottom:20px;border-bottom:3px solid #1a1a2e;padding-bottom:16px">
    <div style="font-size:11px;color:#666;text-transform:uppercase;letter-spacing:1px">Washington State</div>
    <div style="font-size:22px;font-weight:bold;margin:4px 0">${session.form?.form_name}</div>
    <div style="font-size:11px;color:#666">RCW 64.06 · Generated by AIREA on ${today}</div>
  </div>

  <!-- Property & Seller Info -->
  <table style="width:100%;margin-bottom:24px;border:1px solid #ddd;border-collapse:collapse">
    <tr style="background:#f9f9f9">
      <td style="padding:10px 12px;width:50%;border-right:1px solid #ddd">
        <div style="font-size:11px;color:#888;text-transform:uppercase;margin-bottom:2px">Property Address</div>
        <div style="font-size:14px;font-weight:bold">${session.property_address}</div>
      </td>
      <td style="padding:10px 12px;width:25%;border-right:1px solid #ddd">
        <div style="font-size:11px;color:#888;text-transform:uppercase;margin-bottom:2px">Seller Name</div>
        <div style="font-size:14px">${session.seller_name || '________________________'}</div>
      </td>
      <td style="padding:10px 12px;width:25%">
        <div style="font-size:11px;color:#888;text-transform:uppercase;margin-bottom:2px">Date</div>
        <div style="font-size:14px">${today}</div>
      </td>
    </tr>
  </table>

  <!-- Legal Notice -->
  <div style="background:#fff8e1;border:1px solid #ffc107;padding:10px 14px;margin-bottom:24px;font-size:12px;line-height:1.5">
    <strong>SELLER'S DUTY TO DISCLOSE:</strong> Seller is obligated under RCW 64.06 to disclose to a buyer all known material defects affecting the property.
    This duty exists whether or not the buyer asks about those defects. Failure to disclose known material defects can result in legal liability.
    Seller certifies that the information below is accurate and complete to the best of Seller's knowledge as of the date signed.
  </div>

  <!-- Questions by Section -->
  ${sectionsHtml}

  <!-- Signature Block -->
  <div style="margin-top:40px;border-top:2px solid #1a1a2e;padding-top:24px">
    <div style="font-weight:bold;font-size:14px;margin-bottom:16px">SELLER CERTIFICATION</div>
    <p style="font-size:12px;line-height:1.6;margin-bottom:24px">
      The seller hereby certifies that the information contained in this Seller Disclosure Statement is complete, accurate, and correct
      to the best of seller's knowledge and belief as of the date signed below. Seller authorizes any licensed real estate
      licensee to provide a copy of this disclosure to any prospective buyer or buyer's agent.
    </p>

    <table style="width:100%;border-collapse:collapse">
      <tr>
        <td style="width:50%;padding-right:30px">
          <div style="border-bottom:1px solid #000;margin-bottom:6px;height:40px;${session.status === 'signed' ? `display:flex;align-items:flex-end;font-family:Georgia,serif;font-size:18px;font-style:italic;padding-bottom:2px` : ''}">
            ${session.status === 'signed' ? (session.seller_name || '') : ''}
          </div>
          <div style="font-size:11px;color:#666">Seller Signature</div>
        </td>
        <td style="width:25%;padding-right:30px">
          <div style="border-bottom:1px solid #000;margin-bottom:6px;height:40px;display:flex;align-items:flex-end;padding-bottom:4px;font-size:13px">
            ${session.status === 'signed' ? (session.seller_name || '') : ''}
          </div>
          <div style="font-size:11px;color:#666">Printed Name</div>
        </td>
        <td style="width:25%">
          <div style="border-bottom:1px solid #000;margin-bottom:6px;height:40px;display:flex;align-items:flex-end;padding-bottom:4px;font-size:13px">
            ${session.status === 'signed' ? today : ''}
          </div>
          <div style="font-size:11px;color:#666">Date</div>
        </td>
      </tr>
    </table>
  </div>

  <!-- Footer -->
  <div style="margin-top:40px;text-align:center;font-size:10px;color:#999;border-top:1px solid #eee;padding-top:12px">
    Generated by AIREA · AI-Powered Real Estate · This document was prepared using AIREA's disclosure engine.
    Sellers are responsible for the accuracy of all disclosed information. This is not legal advice.
  </div>
</body>
</html>`;

  // Save document record
  const { data: doc, error } = await supabase
    .from('disclosure_documents')
    .upsert({
      session_id: sessionId,
      document_type: 'html',
      content: html,
      is_signed: session.status === 'signed',
    }, { onConflict: 'session_id' })
    .select()
    .single();

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json({ document_id: doc.id, html });
}
